trabajo/green/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .import views

app_name = "green"

urlpatterns = [
    path("",views.home, name="home.html"),
    path("Basica_Matematicas_primero/",views.m1, name="Basica_Matematicas_primero"),
    path("Basica_Lenguaje_primero/",views.l1, name="Basica_Lenguaje_primero"),
    path("Basica_Ciencias_primero/",views.c1, name="Basica_Ciencias_primero"),
    path("Basica_Historia_primero/",views.h1, name="Basica_Historia_primero"),
    path("Basica_Otros_primero/",views.o1, name="Basica_Otros_primero"),
    path("Basica_Ingles_primero/",views.i1, name="Basica_Ingles_primero"),
    path("Basica_Matematicas_segundo/",views.m2, name="Basica_Matematicas_segundo"),
    path("Basica_Lenguaje_segundo/",views.l2, name="Basica_Lenguaje_segundo"),
    path("Basica_Ciencias_segundo/",views.c2, name="Basica_Ciencias_segundo"),
    path("Basica_Historia_segundo/",views.h2, name="Basica_Historia_segundo"),
    path("Basica_Otros_segundo/",views.o2, name="Basica_Otros_segundo"),
    path("Basica_Ingles_segundo/",views.i2, name="Basica_Ingles_segundo"),
    path("Basica_Matematicas_tercero/",views.m3, name="Basica_Matematicas_tercero"),
    path("Basica_Lenguaje_tercero/",views.l3, name="Basica_Lenguaje_tercero"),
    path("Basica_Ciencias_tercero/",views.c3, name="Basica_Ciencias_tercero"),
    path("Basica_Historia_tercero/",views.h3, name="Basica_Historia_tercero"),
    path("Basica_Otros_tercero/",views.o3, name="Basica_Otros_tercero"),
    path("Basica_Ingles_tercero/",views.i3, name="Basica_Ingles_tercero"),
    path("Basica_Matematicas_cuarto/",views.m4, name="Basica_Matematicas_cuarto"),
    path("Basica_Lenguaje_cuarto/",views.l4, name="Basica_Lenguaje_cuarto"),
    path("Basica_Ciencias_cuarto/",views.c4, name="Basica_Ciencias_cuarto"),
    path("Basica_Historia_cuarto/",views.h4, name="Basica_Historia_cuarto"),
    path("Basica_Otros_cuarto/",views.o4, name="Basica_Otros_cuarto"),
    path("Basica_Ingles_cuarto/",views.i4, name="Basica_Ingles_cuarto"),
    path("Basica_Matematicas_quinto/",views.m5, name="Basica_Matematicas_quinto"),
    path("Basica_Lenguaje_quinto/",views.l5, name="Basica_Lenguaje_quinto"),
    path("Basica_Ciencias_quinto/",views.c5, name="Basica_Ciencias_quinto"),
    path("Basica_Historia_quinto/",views.h5, name="Basica_Historia_quinto"),
    path("Basica_Otros_quinto/",views.o5, name="Basica_Otros_quinto"),
    path("Basica_Ingles_quinto/",views.i5, name="Basica_Ingles_quinto"),
    path("Basica_Matematicas_sexto/",views.m6, name="Basica_Matematicas_sexto"),
    path("Basica_Lenguaje_sexto/",views.l6, name="Basica_Lenguaje_sexto"),
    path("Basica_Ciencias_sexto/",views.c6, name="Basica_Ciencias_sexto"),
    path("Basica_Historia_sexto/",views.h6, name="Basica_Historia_sexto"),
    path("Basica_Otros_sexto/",views.o6, name="Basica_Otros_sexto"),
    path("Basica_Ingles_sexto/",views.i6, name="Basica_Ingles_sexto"),
    path("Basica_Matematicas_septimo/",views.m7, name="Basica_Matematicas_septimo"),
    path("Basica_Lenguaje_septimo/",views.l7, name="Basica_Lenguaje_septimo"),
    path("Basica_Ciencias_septimo/",views.c7, name="Basica_Ciencias_septimo"),
    path("Basica_Historia_septimo/",views.h7, name="Basica_Historia_septimo"),
    path("Basica_Otros_septimo/",views.o7, name="Basica_Otros_septimo"),
    path("Basica_Ingles_septimo/",views.i7, name="Basica_Ingles_septimo"),
    path("Basica_Matematicas_octavo/",views.m8, name="Basica_Matematicas_octavo"),
    path("Basica_Lenguaje_octavo/",views.l8, name="Basica_Lenguaje_octavo"),
    path("Basica_Ciencias_octavo/",views.c8, name="Basica_Ciencias_octavo"),
    path("Basica_Historia_octavo/",views.h8, name="Basica_Historia_octavo"),
    path("Basica_Otros_octavo/",views.o8, name="Basica_Otros_octavo"),
    path("Basica_Ingles_octavo/",views.i8, name="Basica_Ingles_octavo"),
    path('post/', views.create_post, name= 'create-post'),
]

trabajo/trabajo/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("green.urls", namespace="green")),
    path("",include("users.urls",namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trabajo/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/<slug:slug>', views.user_detail, name='user_detail'),
    path("follow/<slug:slug>", views.follow, name='follow'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
]

trabajo/templates/pruebas/cursos.html
{% extends "./plantilla.html" %}

{% block cursos %}
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop1"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    1°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop1">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop2"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    2°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop2">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop3"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    3°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop3">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop4"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    4°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop4">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop5"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    5°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop5">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop6"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    6°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop6">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop7"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    7°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop7">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop8"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    8°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop8">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Ciencias Naturales </a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop9"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    I°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop9">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    <li><a class="dropdown-item" href="#">Física </a></li>
    <li><a class="dropdown-item" href="#">Química </a></li>
    <li><a class="dropdown-item" href="#">Biología </a></li>
    <li><a class="dropdown-item" href="#">Otros </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop10"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    II°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop10">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    <li><a class="dropdown-item" href="#">Física </a></li>
    <li><a class="dropdown-item" href="#">Química </a></li>
    <li><a class="dropdown-item" href="#">Biología </a></li>
    <li><a class="dropdown-item" href="#">Otros </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop11"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    III°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop11">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Matemáticas avanzadas</a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    <li><a class="dropdown-item" href="#">Física </a></li>
    <li><a class="dropdown-item" href="#">Química </a></li>
    <li><a class="dropdown-item" href="#">Biología </a></li>
    <li><a class="dropdown-item" href="#">Física avanzada </a></li>
    <li><a class="dropdown-item" href="#">Química avanzada</a></li>
    <li><a class="dropdown-item" href="#">Biología avanzada</a></li>
    <li><a class="dropdown-item" href="#">Otros </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop12"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    IV°
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop12">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Matemáticas avanzadas</a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Ingles </a></li>
    <li><a class="dropdown-item" href="#">Física </a></li>
    <li><a class="dropdown-item" href="#">Química </a></li>
    <li><a class="dropdown-item" href="#">Biología </a></li>
    <li><a class="dropdown-item" href="#">Física avanzada </a></li>
    <li><a class="dropdown-item" href="#">Química avanzada</a></li>
    <li><a class="dropdown-item" href="#">Biología avanzada</a></li>
    <li><a class="dropdown-item" href="#">Otros </a></li>
    </ul>
    
</div>
<div class="btn-group" role="group">
    <button
    id="btnGroupVerticalDrop13"
    type="button"
    class="btn btn-primary dropdown-toggle"
    data-mdb-toggle="dropdown"
    aria-expanded="false"
    >
    PDT
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupVerticalDrop13">
    <li><a class="dropdown-item" href="#">Lenguaje y comunicación </a></li>
    <li><a class="dropdown-item" href="#">Matemáticas</a></li>
    <li><a class="dropdown-item" href="#">Matemáticas avanzadas</a></li>
    <li><a class="dropdown-item" href="#">Historia, Geografía y Ciencias Sociales </a></li>
    <li><a class="dropdown-item" href="#">Física </a></li>
    <li><a class="dropdown-item" href="#">Química </a></li>
    <li><a class="dropdown-item" href="#">Biología </a></li>
    <li><a class="dropdown-item" href="#">Física avanzada </a></li>
    <li><a class="dropdown-item" href="#">Química avanzada</a></li>
    <li><a class="dropdown-item" href="#">Biología avanzada</a></li>
    <li><a class="dropdown-item" href="#">Otros </a></li>
    </ul>
    
</div>
{% endblock %}

trabajo/templates/pruebas/f.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!-- Navbar brand -->
        <a class="navbar-brand mt-2 mt-lg-0" href="#">
          <img
            src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png"
            height="15"
            alt=""
            loading="lazy"
          />
        </a>
        <!-- Left links -->
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Team</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Projects</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
  
      <!-- Right elements -->
      <div class="d-flex align-items-center">
        <!-- Icon -->
        <a class="text-reset me-3" href="#">
          <i class="fas fa-shopping-cart"></i>
        </a>
  
        <!-- Notifications -->
        <a
          class="text-reset me-3 dropdown-toggle hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">1</span>
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">Some news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Another news</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Something else here</a>
          </li>
        </ul>
  
        <!-- Avatar -->
        <a
          class="dropdown-toggle d-flex align-items-center hidden-arrow"
          href="#"
          id="navbarDropdownMenuLink"
          role="button"
          data-mdb-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="https://mdbootstrap.com/img/new/avatars/2.jpg"
            class="rounded-circle"
            height="25"
            alt=""
            loading="lazy"
          />
        </a>
        <ul
          class="dropdown-menu dropdown-menu-end"
          aria-labelledby="navbarDropdownMenuLink"
        >
          <li>
            <a class="dropdown-item" href="#">My profile</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Settings</a>
          </li>
          <li>
            <a class="dropdown-item" href="#">Logout</a>
          </li>
        </ul>
      </div>
      <!-- Right elements -->
        
    </div>
    <!-- Container wrapper -->
  </nav>
  <!-- Navbar -->



  {% include "users/login.html" %}
  <header>
    <nav class="navbar shadow navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img
            src="https://logos-marcas.com/wp-content/uploads/2020/01/Garnier-Logo.png"
            class="me-2" height="45" alt="" loading="lazy" />
          <small>GreeNBooK</small>
          
        </a>
        
        <div class="d-flex align-items-center me-3">
          {% if user.is_authenticated %}
          <a href={% url 'users:profile' %}>
            <img src={{ user.profile_pic.url }} class="rounded-circle" height="30" width='30' alt="" loading="lazy" />
          </a>
          {% else %}
          <button type="button" class="btn btn-primary" data-mdb-toggle='modal' data-mdb-target='#loginModal'>
            Iniciar Sesión
          </button>
          {% endif %}